# Generated by Django 5.1.7 on 2025-04-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coderr_market_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offers",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="offers",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
